apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  ports:
  - port: 8888
    name: http
    targetPort: 80
  selector:
    app: jupyter
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  containers:
    - name: jupyter
      #image: skippbox/jupyter:0.0.3
      image: mjbright/skippbox-jupyter:latest
      ports:
      - containerPort: 80
        protocol: TCP
        name: http
      volumeMounts:
        - mountPath: /root/notebook-volume
          name: notebook-volume
        - mountPath: /root/.kube
          name: kube-config
  volumes:
    - name: notebook-volume
      gitRepo:
        repository: "https://github.com/mjbright/kubernetes-client-python.git"
    - name: kube-config
      hostPath:
        path: /home/core/.kube

